### ISSUE TITLE
taunts arent working

### ISSUE THREAD

**Issue by brotendo5000** [x07x08/TF2-Econ-Taunts#3]
it gives this error in my error log 

L 04/21/2024 - 00:39:48: SourceMod error session started
L 04/21/2024 - 00:39:48: Info (map "ctf_2fort_jungle_rc2") (file "")
L 04/21/2024 - 00:39:48: [SM] Exception reported: Unable to initialize call to CTFPlayer::PlayTauntSceneFromItem.
L 04/21/2024 - 00:39:48: [SM] Blaming: TF2EconTaunts.smx
L 04/21/2024 - 00:39:48: [SM] Call stack trace:
L 04/21/2024 - 00:39:48: [SM]   [0] SetFailState
L 04/21/2024 - 00:39:48: [SM]   [1] Line 163, D:\Stuff\TF2 Things\Sourcepawn Programming\SPCode.Beta.Portable\sourcepawn\scripts\TF2EconTaunts.sp::PlayTaunt
L 04/21/2024 - 00:39:48: [SM]   [2] Line 97, D:\Stuff\TF2 Things\Sourcepawn Programming\SPCode.Beta.Portable\sourcepawn\scripts\TF2EconTaunts.sp::TauntMenuHandler

**Comment by brotendo5000** [comment]
im not sure if its a problem with my server or the plugin all i know is it isnt working but everything else i have is

**Comment by x07x08** [comment]
The signature for `CTFPlayer::PlayTauntSceneFromItem` has changed, I don't know how to do signature scanning and I'm not willing to go through that hassle.
Maybe [this](https://github.com/Batfoxkid/TF2-Custom-Taunts) or [the original](https://github.com/FlaminSarge/tf_tauntem) will have updated signatures in the near future, but until then actual taunting is broken.

**Comment by gdfsgdfg** [comment]
The signature for windows is broken but I think linux is fine. Maybe you can contact noscoop.

**Comment by x07x08** [comment]
I've pushed an updated signature, taunting worked on my end. I'll close this for now.

**Comment by brotendo5000** [comment]
some of the unsual effects are shown as white text in the menu and dont work and as spy none of the taunts seem to want to work it says " [SM] couldnt play taunt "

**Comment by brotendo5000** [comment]
i havent checked other classes i just noticed this
