### ISSUE TITLE
unusual taunts 

### ISSUE THREAD

**Issue by brotendo5000** [x07x08/TF2-Econ-Taunts#4]
some of the unusual effects show as white text and wont enable

**Comment by x07x08** [comment]
You mentioned this in #3 as well and I am going to assume you haven't opened the [configuration file](https://github.com/x07x08/TF2-Econ-Taunts/blob/main/addons/sourcemod/configs/econtaunts/taunts.cfg).

**Comment by brotendo5000** [comment]
my bad that completely slipped my mind

**Comment by brotendo5000** [comment]
thank you
